controller_manager:
  ros__parameters:
    defaults:
      allow_controller_activation_with_inactive_hardware: false
      deactivate_controllers_on_hardware_self_deactivate: true
      switch_controller:
        strictness: strict

    diagnostics:
      threshold:
        controller_manager:
          periodicity:
            mean_error:
              error: 10.0
              warn: 5.0
            standard_deviation:
              error: 10.0
              warn: 5.0
        controllers:
          execution_time:
            mean_error:
              error: 200.0
              warn: 100.0
            standard_deviation:
              error: 20.0
              warn: 10.0
          periodicity:
            mean_error:
              error: 10.0
              warn: 5.0
            standard_deviation:
              error: 10.0
              warn: 5.0
        hardware_components:
          execution_time:
            mean_error:
              error: 200.0
              warn: 100.0
            standard_deviation:
              error: 20.0
              warn: 10.0
          periodicity:
            mean_error:
              error: 10.0
              warn: 5.0
            standard_deviation:
              error: 10.0
              warn: 5.0

    enforce_command_limits: true
    handle_exceptions: true
    hardware_components_initial_state:
      inactive:
        - MoteusHardwareSystem
      shutdown_on_initial_state_failure: false
    overruns:
      print_warnings: true
    update_rate: 100

    lock_memory: true
    thread_priority: 99

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    teleop_controller:
      type: robotarm_controllers/TeleopController

MoteusHardwareSystem:
  ros__parameters:
    execution_mode: "pipelined"  # pipelined or strict_sequential
    transport_mode: "udp"        # "udp" or "usb"
    udp_ip: "192.168.22.200"
    udp_port: 6666
    usb_device: "/dev/fdcanusb"

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50

teleop_controller:
  ros__parameters:
    joints:
      - axis1
      - axis2
      - axis3
    command_interfaces:
      - position
      - velocity
    max_velocity: 3.0
    max_acceleration: 4.0
    max_jerk: 10.0
    sync_joints: false